services:
  backend:
    build: .
    container_name: hospital-backend
    ports:
      - "9090:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  frontend:
    build: ../hospital-queue-frontend
    container_name: hospital-frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
